[package]
name = "z33-cli"
description = "An emulator for the Zorglub-33 architecture"
homepage = "https://pdagog.gitlab.io/ens/z33refcard.pdf"
version = "0.3.0"
authors = ["Quentin Gliech <gliech@unistra.fr>"]
edition = "2018"
readme = "../README.md"
license = "MIT"

[dependencies]
z33-emulator = { path = "../emulator" }
tracing = "0.1.29"
tracing-subscriber =  { version = "0.3.3", features = ["env-filter", "json"] }
rustyline = "9.0.0"
rustyline-derive = "0.5.0"
clap = "3.0.0-beta.5"
shell-words = "1.0.0"
ansi_term = "0.12.1"
clap_generate = "3.0.0-beta.5"
atty = "0.2.14"
nom = "7.1.0"
anyhow = "1.0.51"
thiserror = "1.0.30"
