[package]
name = "z33-cli"
description = "An emulator for the Zorglub-33 architecture"
homepage = "https://pdagog.gitlab.io/ens/z33refcard.pdf"
version = "0.5.0"
authors = ["Quentin Gliech <gliech@unistra.fr>"]
edition = "2021"
readme = "../README.md"
license = "MIT"

[dependencies]
z33-emulator = { path = "../emulator" }
tracing = "0.1.36"
tracing-subscriber =  { version = "0.3.15", features = ["env-filter", "json"] }
rustyline = "10.0.0"
rustyline-derive = "0.7.0"
clap = { version = "3.2.16", features = ["derive"] }
shell-words = "1.1.0"
ansi_term = "0.12.1"
clap_complete = "3.2.3"
atty = "0.2.14"
nom = "7.1.1"
anyhow = "1.0.58"
thiserror = "1.0.31"
codespan-reporting = { git = "https://github.com/brendanzab/codespan.git" }
