[package]
name = "z33-emulator"
description = "An emulator for the Zorglub-33 architecture"
homepage = "https://pdagog.gitlab.io/ens/z33refcard.pdf"
version = "0.3.0"
authors = ["Quentin Gliech <gliech@unistra.fr>"]
edition = "2018"
readme = "../README.md"
license = "MIT"

[dependencies]
bitflags = "1.2.1"
thiserror = "1.0.24"
nom = "6.1.2"
tracing = "0.1.24"
tracing-subscriber = "0.2.16"
unicode-segmentation = "1.7.1"

[dev-dependencies]
indoc = "1.0.3"
