[package]
name = "z33-emulator"
description = "An emulator for the Zorglub-33 architecture"
homepage = "https://pdagog.gitlab.io/ens/z33refcard.pdf"
version = "0.1.0"
authors = ["Quentin Gliech <gliech@unistra.fr>"]
edition = "2018"
readme = "../README.md"
license = "MIT"

[dependencies]
bitflags = "1.2.1"
z33_instruction_derive = { path = "../instruction-derive" }
thiserror = "1.0.20"
nom = "5.1.2"
tracing = "0.1.19"
tracing-subscriber = "0.2.12"
regex = "1.3.9"
unicode-segmentation = "1.6.0"
rustyline = "6.2.0"
rustyline-derive = "0.3.1"
clap = "3.0.0-beta.2"
shell-words = "1.0.0"
ansi_term = "0.12.1"
