[package]
name = "z33-emulator"
description = "An emulator for the Zorglub-33 architecture"
homepage = "https://pdagog.gitlab.io/ens/z33refcard.pdf"
version = "0.3.0"
authors = ["Quentin Gliech <gliech@unistra.fr>"]
edition = "2018"
readme = "../README.md"
license = "MIT"

[dependencies]
bitflags = "1.3.2"
thiserror = "1.0.29"
nom = "7.0.0"
tracing = "0.1.29"
tracing-subscriber = "0.2.25"
unicode-segmentation = "1.8.0"
parse-display = "0.5.3"

[dev-dependencies]
indoc = "1.0.3"
pretty_assertions = "1.0.0"
