[package]
name = "z33-emulator"
description = "An emulator for the Zorglub-33 architecture"
homepage = "https://pdagog.gitlab.io/ens/z33refcard.pdf"
version = "0.5.3"
authors = ["Quentin Gliech <gliech@unistra.fr>"]
edition = "2021"
readme = "../README.md"
license = "MIT"

[dependencies]
bitflags = "2.0.2"
thiserror = "1.0.40"
nom = "7.1.3"
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
unicode-segmentation = "1.10.1"
parse-display = "0.8.0"

[dev-dependencies]
indoc = "2.0.1"
pretty_assertions = "1.3.0"
