[package]
name = "z33-emulator"
version = "0.1.0"
authors = ["Quentin Gliech <quentingliech@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "1.2.1"
z33_instruction_derive = { path = "../instruction-derive" }
thiserror = "1.0.20"
nom = "5.1.2"
tracing = "0.1.19"
tracing-subscriber = "0.2.11"
regex = "1.3.9"
unicode-segmentation = "1.6.0"
rustyline = "6.2.0"
rustyline-derive = "0.3.1"
clap = "3.0.0-beta.1"
shell-words = "1.0.0"
ansi_term = "0.12.1"
